### ISSUE TITLE
Add a frequency to squawk mapping

### ISSUE THREAD

**Issue by 76rhodan** [rpatel3001/docker-acars2pos#2]
Hi,

it would be great to have a dumphfdl like frequency to squawk mapping as option in acars2pos.
That would come very handy with the extended HF markers for VRS. All flights will be color coded according to the frequency over which the data / position was received.

**Comment by rpatel3001** [comment]
first pass done, need to work out readsb/tar1090 display with wiedehopf

**Comment by rpatel3001** [comment]
@wiedehopf Any chance of a readsb update to allow slightly more decimal digits to get through or is that too much of a change to support a nonstandard use of the squawk field? I think VRS works fine so @76rhodan and @rikgale are happy without it.

**Comment by wiedehopf** [comment]
That's why i suggested using altitude.
It's a bit of a pain and more of a pain to allow > 65000 ...

**Comment by rikgale** [comment]
If you have the code for FREQ_TO_SQUAWK, can you not add to that to also do FREQ_TO_ALT?

**Comment by rpatel3001** [comment]
Yeah I can add freq to alt.

Only need up to 37000 for squawk if that makes it simpler since I'm dropping the first 1 digit for acars/vdl

**Comment by rpatel3001** [comment]
freq to alt added
